apiVersion: v1
kind: Service
metadata:
  name: deis-riak-discovery
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - port: 4369
      targetPort: 4369
      name: epmd
      protocol: TCP
    - port: 6001
      targetPort: 6001
      name: inetd
      protocol: TCP
    - port: 8087
      targetPort: 8087
      name: http
      protocol: TCP
    - port: 8098
      targetPort: 8098
      name: protobuf
      protocol: TCP
    - port: 8099
      targetPort: 8099
      name: handoff
      protocol: TCP
    - port: 8080
      targetPort: 8080
      name: plansrv
      protocol: TCP
  selector:
    name: riak
  clusterIP: None
