apiVersion: v1
kind: Service
metadata:
  name: riak
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
    - port: 8087
      targetPort: 8087
      name: http
      protocol: TCP
    - port: 8098
      targetPort: 8098
      name: protobuf
      protocol: TCP
  selector:
    name: riak
